tango_with_django_project/rango/urls.py
#!/usr/bin/env python3
# encoding: utf-8

from django.conf.urls import url, include
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_profile/$', views.register_profile, name='register_profile'),
    url(r'^like_category/$', views.like_category, name='like_category'),
    url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
    url(r'^goto//?page_id=(?P<page_id>[\d+])/$', views.track_url, name='track_url'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout'),
    # url(r'^restricted/$', views.restricted, name='restricted'),
    # url(r'^register/$', views.register, name='register'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^add_page_from_search/$', views.add_page_from_search, name='add_page_from_search'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page,
        name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category,
        name='show_category'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from rango import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/rango/')),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views < 0:
            self.views = 0
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
#!/usr/bin/env python3
# encoding: utf-8

from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )


class SearchForm(forms.ModelForm):
    query = forms.CharField(help_text="Please enter what you want to search.")


class PageForm(forms.ModelForm):
    title = forms.CharField(
        max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(
        max_length=200, help_text="Please enter the url of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category', )

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
from datetime import datetime
from django.shortcuts import render
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm, SearchForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from rango import bing_search


def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
            return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context=context_dict)
    # response.set_cookie('visits', context_dict['visits'])
    return response


def search(request):
    if request.method == "POST":
        form = request.POST
        query = form['query'].strip()
        results = [{}]
        try:
            results = bing_search.run_query(query)
        except IOError:
            results[0]['title'] = 'bing.key file not found!'
        except KeyError:
            results[0]['title'] = 'key not found!'
        except Warning:
            results[0][
                'title'] = 'Search Error, check the key file and web connection!'
        context_dict = {'results': results, 'query': query}
    else:
        context_dict = None
    return render(request, 'rango/search.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['category'] = category
        context_dict['pages'] = pages
        if request.method == "POST":
            form = request.POST
            query = form['query'].strip()
            results = [{}]
            try:
                results = bing_search.run_query(query)
            except IOError:
                results[0]['title'] = 'bing.key file not found!'
            except KeyError:
                results[0]['title'] = 'key not found!'
            except Warning:
                results[0][
                    'title'] = 'Search Error, check the key file and web connection!'
            context_dict['results'] = results
            context_dict['query'] = query
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context=context_dict)


def about(request):
    if request.session.test_cookie_worked():
        print('Test Cookie worked!')
        request.session.delete_test_cookie()
    context_dict = {'yourname': 'Jase Chen'}
    print('request method:', request.method)
    print('Login User:', request.user)
    return render(request, 'rango/about.html', context=context_dict)


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(
        request, 'rango/register.html', {
            'user_form': user_form,
            'profile_form': profile_form,
            'registered': registered,
        })


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                return HttpResponse('Your rango account is disable.')
        else:
            print('Invalid login details: {}, {}'.format(username, password))
            return HttpResponse('Invalid login details supplied.')
    else:
        return render(request, 'rango/login.html', {})


@login_required
def restricted(request):
    return HttpResponse('Since you logged in you can see this page!')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit',
                                               str(datetime.now())[:-7])
    last_visit_time = datetime.strptime(last_visit_cookie, '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).seconds > 1:
        visits += 1
        request.session['last_visit'] = str(datetime.now())[:-7]
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits


def track_url(request, page_id):
    if request.method == 'GET':
        page = Page.objects.get(id=page_id)
        page.views += 1
        page.save()
        return HttpResponseRedirect(page.url)


def register_profile(request):
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.save()
    return render(request, 'rango/profile_registration.html', {})


@login_required
def like_category(request):
    cat_id = None
    if request.method == "GET":
        cat_id = request.GET['category_id']
    likes = 0
    if cat_id:
        cat = Category.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes + 1
            cat.likes = likes
            cat.save()
    return HttpResponse(likes)


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(slug__startswith=starts_with)
        print('get_category list:', cat_list)
    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list


def suggest_category(request):
    print('Start to Search...'.center(50, '-'))
    cat_list = []
    starts_with = ''
    if request.method == "GET":
        starts_with = request.GET['suggestion'].lower()
        print('starts_with: {}'.format(starts_with))
    cat_list = get_category_list(max_results=8, starts_with=starts_with)
    print('query_category list:', cat_list)
    return render(request, 'rango/category_list.html', {'cat_list': cat_list})


@login_required
def add_page_from_search(request):
    print('start to add page')
    if request.method == 'GET':
        title = request.GET['title']
        url = request.GET['link']
        category_id = request.GET['category_id']
        category = Category.objects.get(id=category_id)
        page = Page.objects.get_or_create(category=category, title=title, url=url)
    page_list = Page.objects.filter(category=category).order_by('-views')
    return render(request, 'rango/page_list.html', {'page_list': page_list})

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
  About
{% endblock %}
{% block body_block %}
  <h1 class="h1">Hi there!</h1>
  <p>Rango says here is the about page!
    <p>Click
    <a href="{% url 'rango:index' %}" target="_self">Here</a>
      back to the Home page
    </p>
    <p>This tutorial has been put together by {{ yourname }}</p>
  </p>
  <button onClick="alert('You clicked the button using JavaScript.');">Click me - I run JavaScript</button>
  <br>
  <br>
  <button id="about-btn">Click me - I'm JavaScript on speed</button>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
  Add a Category!
{% endblock %}
{% block body_block %}
    <form role="form" id="category_form" action="{% url 'rango:add_category' %}" method="post" accept-charset="utf-8">
        <h2 class="form-signin-heading">Add a Category</h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }} <br />
            {{ field }} <br />
        {% endfor %}
        <br />
        <!--<input type="submit" value="Creat Category" name="submit" id="submit"/>-->
        <button class="btn btn-primary" type="submit" name="submit">Add a Category</button>
    </form>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
  Add a page in {{ category.name }}
{% endblock %}
{% block body_block %}
    {% if category %}
    <form role="form" id="page_form" action="{% url 'rango:add_page' category.slug %}" method="post" accept-charset="utf-8">
        <h2 class="form-signin-heading">Add a Page to
            <a href="{% url 'rango:show_category' category.slug %}">
                {{ category.name }}</a>
        </h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }} <br />
            {{ field }} <br />
        {% endfor %}
        <br />
        <!--<input type="submit" value="Creat Page" name="submit" id="submit"/>-->
        <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
        </form>
    {% else %}
        <p>Category does not exist!</p>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="zh-cn">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,
                                    initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
      Rango -
      {% block title_block %}
        How to Tango with Django!
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="{% url 'rango:index' %}" class="navbar-brand">Rango</a>
        <button type="button" class="navbar-toggler"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'rango:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <!--<li class="nav-item">-->
                    <!--<a class="nav-item nav-link" href="{% url 'rango:search' %}">Search</a>-->
                <!--</li>-->
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
                </li>
                    {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'rango:register_profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'auth_logout'  %}?next={% url 'rango:index' %}">Logout</a>
                </li>
                    {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'registration_register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'auth_login' %}">Login</a>
                </li>
                    {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-list">
                    <li class="nav-header">Find a Category</li>
                    <form>
                        <label></label>
                        <li>
                            <input class="search-query span10" type="text" value="" name="suggestion" id="suggestion"/>
                        </li>
                    </form>
                </ul>
                <div id="cats">
                </div>
                <br>
                {% block sidebar_block %}
                    {% get_category_list category %}
                {% endblock %}
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                {% block body_block %}
                {% endblock %}
            </div>
        </div>
    </div>
    <!--bootstrap-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <!--jQuery-->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/rango-ajax.js' %}"></script>
  </body>
</html>

tango_with_django_project/templates/rango/base_bak.html
<!DOCTYPE html>

{% load rango_template_tags %}
{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>
      Rango -
      {% block title_block %}
        How to Tango with Django!
      {% endblock %}
    </title>
  </head>
  <body>
    {% if user.is_authenticated %}
        Hello {{ user.username }}
    {% else %}
        Hello my friend!
    {% endif %}
    {% block body_block %}
    {% endblock %}
    <hr />
    <div>
      {% block sidebar_block %}
        {% get_category_list category %}
      {% endblock %}
    </div>
    <hr />
    <div>
      <ul>
        <li><a href="{% url 'rango:index' %}" target="_self">Index</a></li>
        <li><a href="{% url 'rango:about' %}" target="_self">About</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'rango:add_category' %}" target="_self">New Category</a></li>
            <li><a href="{% url 'auth_logout' %}?next=/" target="_self">LogOut</a></li>
            <li><a href="{% url 'auth_password_change' %}" target="_self">Change Password</a></li>
        {% else %}
            <li><a href="{% url 'registration_register' %}" target="_self">Sign Up</a></li>
            <li><a href="{% url 'auth_login' %}" target="_self">Login</a></li>
        {% endif %}
        <p>
            visitors: {{ visits }}
        </p>
      </ul>
    </div>
  </body>
</html>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
  {{ category.name }}
{% endblock %}
{% block body_block %}
  {% if category %}
    <p><h1>{{ category.name }}</h1>
        <strong id="like_count">{{ category.likes }}</strong>likes
        <br>
        {% if user.is_authenticated %}
        <button type="button" id="likes" data-catid="{{ category.id }}" class="brn btn-primary">
            Like
            <span class="glyphicon glyphicon-thumbs-up"></span>
        </button>
        {% endif %}
    </p>
    {% if pages %}
      <div id="refresh_pages">
        <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}" target="_self">{{ page.title }}</a>
        </li>
        {% endfor %}
        </ul>
      </div>
    {% else %}
      <strong>There's no pages here!</strong>
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}" target="_self">Add a page in this Category</a>
    {% endif %}
  {% else %}
  <strong>The category does not exist!!</strong>
  {% endif %}
  {% if user.is_authenticated %}
    <div>
        <h3>Search with Rango</h3>
        <form class="form-inline" action="{% url 'rango:show_category' category.slug %}" role="form" method="post" id="user_form" accept-charset="utf-8">
        {% csrf_token %}
        <div class="form-row">
            <div class="input-group">
            {% if query %}
            <input type="text" class="form-control form-control-lg" value="{{ query }}" name="query" id="id_query" size="50" />
            {% else %}
            <input type="text" class="form-control form-control-lg" value="" name="query" id="id_query" size="50" placeholder="Search" />
            {% endif %}
            </div>
            <!--<div class="col-12 col-md-2">-->
            <div>
            <button type="submit" class="btn btn-block btn-lg btn-primary"/>Search</button>
            </div>
        </div>
        </form>
        {% if results %}
        {% for result in results %}
        <div id="div_{{ result.link }}">
          <h3><a href="{{ result.link }}">{{ result.title }}</a></h3>
          <p>{{ result.summary }}</p>
          <!--<p><a href="{% url 'rango:show_category' category.slug %}">Add to this Category(待完善)</a></p>-->
          <p><button class="add_button" link="{{ result.link }}" title="{{ result.title }}" category_id="{{ category.id }}">Add to this Category</button></p>
          <hr />
          <br />
        </div>
        {% endfor %}
        {% endif %}
    </div>
  {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/category_list.html
<ul>
  {% if cat_list %}
    <!--<h2>Categories</h2>-->
    {% for c in cat_list %}
      {% if act_cat == c %}
        <li>
          <strong>
            <a href="{% url 'rango:show_category' c.slug %}" target="_self">
              {{ c.name }}</a>
          </strong>
        </li>
      {% else %}
        <li>
          <a href="{% url 'rango:show_category' c.slug %}" target="_self">
            {{ c.name }}</a>
        </li>
      {% endif %}
    {% endfor %}
  {% else %}
    <li><strong>There are no category present.</strong></li>
  {% endif %}
</ul>

tango_with_django_project/templates/rango/cats.html
<ul>
  {% if cats %}
    <!--<h2>Categories</h2>-->
    {% for c in cats %}
      {% if act_cat == c %}
        <li>
          <strong>
            <a href="{% url 'rango:show_category' c.slug %}" target="_self">
              {{ c.name }}</a>
          </strong>
        </li>
      {% else %}
        <li>
          <a href="{% url 'rango:show_category' c.slug %}" target="_self">
            {{ c.name }}</a>
        </li>
      {% endif %}
    {% endfor %}
  {% else %}
    <li><strong>There are no category present.</strong></li>
  {% endif %}
</ul>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block body_block %}
    <div class="jumbotron">
        <h1 class="display-3">Rango says...</h1>
        {% if user.is_authenticated %}
            <h1>Hey {{ user.username }}</h1>
        {% else %}
            <h1>Hey there parter.</h1>
        {% endif %}
    </div>
    <div class="row marketing">
        <div class="col-lg-6">
            <p><h2>Most Liked 5 Categories</h2></p>
            {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item">
                    <a href="{% url 'rango:show_category' category.slug %}" target="_self">{{ category.name }}</a>@{{ category.likes }}likes
                </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>
        <div class="col-lg-6">
            <p><h2>Most Viewed 5 Pages</h2></p>
            {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                <li class="list-group-item">
                    <a href="{% url 'rango:track_url' page.id %}" target="_blank">{{ page.title }}</a>@{{ page.views }}views
                </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no page!!</strong>
            {% endif %}
        </div>
    </div>
    <br \>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango!"/>
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Login
{% endblock %}

{% block body_block %}
    <link rel="stylesheet" href="http://getbootstrap.com/docs/4.1/examples/sign-in//signin.css">
    <div>
        <h1>Login</h1>
    </div>
    <form class="form-signin" action="{% url 'rango:login' %}" role="form" method="post" id="login_form" accept-charset="utf-8">
        {% csrf_token %}
        Username: <input type="text" value="" name="username" id="username" size="50"/>
        <br />
        Password: <input type="password" value="" name="password" id="password" size="50"/>
        <br />
        <input type="submit" value="submit" name="" id=""/>
    </form>
{% endblock %}

tango_with_django_project/templates/rango/page_list.html
<ul>
  {% if page_list %}
    {% for page in page_list %}
        <li>
          <a href="{{ page.url }}" target="_blank">
            {{ page.title }}</a>
        </li>
    {% endfor %}
  {% else %}
    <li><strong>There are no Pages present.</strong></li>
  {% endif %}
</ul>

tango_with_django_project/templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Profile Regsitration
{% endblock %}

{% block body_block %}
  {% if user.is_authenticated %}
    <form id='user_form' action="{% url 'rango:register_profile' %}" method="post" role="form" class="bs-example bs-example-form">
        {% csrf_token %}
        <h2 class="form-signin-heading">Profile Regsitration</h2>
        <div class="input-group">
            <span class="input-group-addon">Username</span>
            <input type="text" value="{{ user.username }}" name="username" class="form-control"/>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Email</span>
            <input type="text" value="{{ user.email }}" name="email" class="form-control"/>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Date-joined</span>
            <input type="text" value="{{ user.date_joined }}" class="form-control"/>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Password</span>
            <input type="text" value="{{ user.password }}" name="password" class="form-control"/>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">提交变更</button>
    </form>
  {% else %}
  Rango says: <a href="{% url 'rango:register' %}"><strong>Regsiter here!</strong></a><br />
  {% endif %}
    <a href="{% url 'rango:index' %}" target="_self">Return to the home page!</a><br />
{% endblock %}

tango_with_django_project/templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
  Search
{% endblock %}
{% block body_block %}
  <div>
    <h1>Search with Rango</h1>
    <form class="form-inline" action="{% url 'rango:search' %}" role="form" method="post" id="user_form" accept-charset="utf-8">
      {% csrf_token %}
      <div class="form-row">
        <div class="input-group">
        <!--<div class="col-10 col-md-9 mb-2 mb-md-0">-->
          {% if query %}
          <input type="text" class="form-control form-control-lg" value="{{ query }}" name="query" id="id_query" size="50" />
          {% else %}
          <input type="text" class="form-control form-control-lg" value="" name="query" id="id_query" size="50" placeholder="Search" />
          {% endif %}
        </div>
        <!--<div class="col-12 col-md-2">-->
        <div>
          <button type="submit" class="btn btn-block btn-lg btn-primary"/>Search</button>
        </div>
      </div>
    </form>
    {% if results %}
      {% for result in results %}
      <h3><a href="{{ result.link }}">{{ result.title }}</a></h3>
      <p>{{ result.summary }}</p>
      <hr />
      <br />
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}